"""Wrap the artifact-body pages in ``site/`` into standalone documents for GitHub Pages.

The files in ``site/`` are artifact *bodies*: no doctype, no ``<head>``. That is
what the Artifact publisher expects, because it supplies the skeleton itself.
Served straight off Pages the same bytes render in quirks mode, with no charset
(the prose carries typographic quotes and minus signs) and no viewport meta, so
they need a skeleton of their own.

This writes that skeleton around each page into ``docs/`` and generates an index.
``site/`` stays the single source of truth; ``docs/`` is derived and regenerated
by ``make pages``.
"""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path

#: Matches the artifact publisher's own skeleton closely enough that a page
#: renders the same way from Pages as it does from the artifact URL.
SKELETON = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>:root{{color-scheme:light}}body{{margin:0;padding:0;font:14px -apple-system,BlinkMacSystemFont,sans-serif;background:#faf9f5;color:#141413}}img{{max-width:100%}}[hidden]:not([hidden=until-found i]){{display:none!important}}</style>
</head>
<body>
{body}
</body>
</html>
"""

INDEX = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>geo-graphs</title>
<style>
:root{{color-scheme:light dark}}
body{{margin:0;background:#faf9f5;color:#141413;
  font:17px/1.6 "Source Serif 4",Georgia,"Times New Roman",serif}}
main{{max-width:34rem;margin:0 auto;padding:clamp(2.5rem,8vw,5rem) 1.4rem}}
h1{{font:800 2rem/1.1 Archivo,"Helvetica Neue",Arial,sans-serif;
  letter-spacing:-.03em;margin:0 0 .6rem}}
p.sub{{color:#5d6b66;margin:0 0 2.4rem}}
a.card{{display:block;padding:.9rem 1.1rem;margin-bottom:.7rem;text-decoration:none;
  color:inherit;background:#fcfcfb;border:1px solid #cdd5d3;border-left:3px solid #0e9384;
  border-radius:2px}}
a.card:hover{{border-color:#a9b5b2;border-left-color:#0e9384}}
a.card .t{{font:600 1rem Archivo,"Helvetica Neue",Arial,sans-serif;display:block}}
a.card .d{{font-size:.88rem;color:#5d6b66;display:block;margin-top:.2rem;line-height:1.45}}
footer{{margin-top:2.4rem;font-size:.88rem;color:#5d6b66}}
footer a{{color:inherit}}
@media (prefers-color-scheme:dark){{
  body{{background:#141917;color:#e8edeb}}
  p.sub,a.card .d,footer{{color:#94a29d}}
  a.card{{background:#1b211f;border-color:#2c3532}}
}}
</style>
</head>
<body>
<main>
<h1>geo-graphs</h1>
<p class="sub">Road graph extraction from overhead imagery. Written up as
self-contained pages; the code is on
<a href="https://github.com/craig-corcoran/geo-graphs">GitHub</a>.</p>
{cards}
<footer>Generated by <code>make pages</code> from <code>site/</code>.</footer>
</main>
</body>
</html>
"""


@dataclass(frozen=True, slots=True)
class Page:
    """One page to wrap, and how the index should describe it."""

    stem: str
    title: str
    blurb: str


PAGES: tuple[Page, ...] = (
    Page(
        "transport_networks",
        "Estimating Transportation Networks from Remote Sensing",
        "The case study: the baseline, what the remaining error is made of, "
        "whether APLS is the right objective, and two extensions measured "
        "before either was built.",
    ),
    Page(
        "where_road_graphs_break",
        "Where Road Graphs Break",
        "The replication and the ceiling argument at more depth, with the four "
        "metric bugs that produced believable numbers.",
    ),
)


def wrap(body: str) -> str:
    """Put a standards-mode skeleton around an artifact body.

    Args:
        body: Page content as published to an artifact, with no doctype or head.

    Returns:
        A complete HTML document.

    Raises:
        ValueError: If the body already carries a skeleton, which would nest.
    """
    if re.search(r"<!doctype|<html[\s>]|<body[\s>]", body, re.I):
        raise ValueError("body already has a skeleton; it would be nested")
    return SKELETON.format(body=body.strip())


def build(site: Path, docs: Path) -> list[Path]:
    """Regenerate ``docs/`` from ``site/``.

    Args:
        site: Directory holding the artifact bodies.
        docs: Output directory, created if absent.

    Returns:
        The files written, index last.
    """
    docs.mkdir(parents=True, exist_ok=True)
    written = [
        _write(docs / f"{page.stem}.html", wrap((site / f"{page.stem}.html").read_text()))
        for page in PAGES
    ]
    cards = "\n".join(
        f'<a class="card" href="{page.stem}.html">'
        f'<span class="t">{page.title}</span>'
        f'<span class="d">{page.blurb}</span></a>'
        for page in PAGES
    )
    return [*written, _write(docs / "index.html", INDEX.format(cards=cards))]


def _write(path: Path, text: str) -> Path:
    path.write_text(text)
    return path


def main() -> None:
    """Regenerate the Pages copies and report what was written."""
    parser = argparse.ArgumentParser(description=__doc__)
    root = Path(__file__).resolve().parent.parent
    parser.add_argument("--site", type=Path, default=root / "site")
    parser.add_argument("--docs", type=Path, default=root / "docs")
    args = parser.parse_args()
    for path in build(args.site, args.docs):
        print(f"{path.relative_to(root)}  {path.stat().st_size:,} bytes")


if __name__ == "__main__":
    main()
